### ISSUE TITLE
setting an array element with a sequence

### ISSUE THREAD

**Issue by LeiYangGH** [eriklindernoren/ML-From-Scratch#110]
PS C:\G\ML-From-Scratch> python mlfromscratch/examples/polynomial_regression.py
Finding regularization constant using cross validation:
Traceback (most recent call last):
  File "C:\G\ML-From-Scratch\mlfromscratch\examples\polynomial_regression.py", line 81, in <module>
    main()
  File "C:\G\ML-From-Scratch\mlfromscratch\examples\polynomial_regression.py", line 32, in main
    cross_validation_sets = k_fold_cross_validation_sets(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.conda\envs\tor\Lib\site-packages\mlfromscratch-0.0.4-py3.12.egg\mlfromscratch\utils\data_manipulation.py", line 145, in k_fold_cross_validation_sets
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (10, 4) + inhomogeneous part.

**Comment by levietnguyen** [comment]
## Simply Change `return np.array(sets)` in `data_manipulation.py` to `return sets`

### **Explanation:**
### **Why Returning `sets` Works Instead of `np.array(sets)`**
The fix works because of how NumPy handles arrays with complex nested structures. Here's why:

### **The Original Problem**
When the code attempted to return `np.array(sets)`, it was trying to convert a list of lists (where each inner list contains arrays of potentially different shapes) into a **homogeneous NumPy array**.

### **Why This Fails**
NumPy arrays are designed to hold elements of the same type and, more importantly, elements that can be arranged in a **regular grid**. When you have a list like `sets` where each element contains:

- `X_train`: A **2D array** with shape **(varying_size, n_features)**
- `X_test`: A **2D array** with shape **(smaller_size, n_features)**
- `y_train`: A **1D array** with shape **(varying_size,)**
- `y_test`: A **1D array** with shape **(smaller_size,)**

NumPy **can't create a regular grid structure** to hold these heterogeneous shapes.

### **What Happens When `np.array(sets)` is Used**
When NumPy tries to convert this irregular structure to an array, it attempts to create what's called a **"ragged array"**—an array where the **size of dimensions can vary**. 

- NumPy **does not directly support ragged arrays**, so it tries to use an **object array** (i.e., an array of Python objects).
- This approach **fails** when the objects themselves have complex, nested structures with **inconsistent dimensions**.

### **Why Returning `sets` Works**
By returning `sets` as a **plain Python list** instead of converting it to a NumPy array:

✅ You **preserve the original structure** without forcing it into a rigid NumPy array format.  
✅ The **consumer code** can iterate through the list and access each fold's data directly.  
✅ Each element **retains its original NumPy array properties** for `X_train`, `X_test`, `y_train`, and `y_test`.  

### **Final Fix:**
Replace:
```python
return np.array(sets)
```
With:
```python
return sets
```
This ensures that the k-fold cross-validation sets remain correctly formatted and usable.

**Comment by Sayyam-Akram** [comment]
Hi! I'm a data science student and would like to fix this issue. 

The problem is that np.array(sets) fails when trying to convert a list of k-fold cross-validation sets with different shapes. The solution is to 
return the plain Python list instead.

I'll also fix the np.append bug on lines 142-143.

Can I work on this?

**Comment by lalala00019** [comment]
Yes sure!
