### ISSUE TITLE
ImportError: when trying example

### ISSUE THREAD

**Issue by aashutoshrathi** [eriklindernoren/ML-From-Scratch#45]
Terminal Session:

```sh
$ python mlfromscratch/examples/polynomial_regression.py
Traceback (most recent call last):
  File "mlfromscratch/examples/polynomial_regression.py", line 6, in <module>
    from mlfromscratch.supervised_learning import PolynomialRidgeRegression
  File "C:\users\aashutosh rathi\appdata\local\programs\python\python36\lib\site-packages\mlfromscratch-0.0.4-py3.6.egg\mlfromscratch\supervised_learning\__init__.py", line 14, in <module>
  File "C:\users\aashutosh rathi\appdata\local\programs\python\python36\lib\site-packages\mlfromscratch-0.0.4-py3.6.egg\mlfromscratch\supervised_learning\support_vector_machine.py", line 4, in <module>

  File "C:\users\aashutosh rathi\appdata\local\programs\python\python36\lib\site-packages\cvxopt-1.2.0-py3.6-win-amd64.egg\cvxopt\__init__.py", line 50, in <module>
    import cvxopt.base
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by RGauthamRam** [comment]
Have you installed the module ? (The one it says as missing/not founf)

**Comment by aashutoshrathi** [comment]
Yes, it was successfully installed.

**Comment by goodhamgupta** [comment]
What version of python are you using? 
It is working for me. I tried installing everything from scratch in a new virtualenv with python3. These are the steps i've followed:

```bash
$ virtualenv .env -p python3
$ source .env/bin/activate
$ pip3 install -r requirements.txt
$ python setup.py install
$ python mlfromscratch/examples/polynomial_regression.py

Finding regularization constant using cross validation:
	Mean Squared Error: 11.236803302856867 (regularization: 0.0)
	Mean Squared Error: 11.691821033072504 (regularization: 0.01)
	Mean Squared Error: 11.454201731415562 (regularization: 0.02)


	Mean Squared Error: 11.787107785520785 (regularization: 0.03)
	Mean Squared Error: 11.552946090789357 (regularization: 0.04)
	Mean Squared Error: 11.792153728713092 (regularization: 0.05)
	Mean Squared Error: 11.748610584156516 (regularization: 0.06)
	Mean Squared Error: 11.789511322709526 (regularization: 0.07)
	Mean Squared Error: 11.800253691555067 (regularization: 0.08)
	Mean Squared Error: 11.854128231962756 (regularization: 0.09)

Mean squared error: 11.236803302856867 (given by reg. factor: 0.0)
```
A plot is displayed after the last line.

**Comment by edchepen** [comment]
I have also run this in a Linux Environment (Ubuntu 16.04), inside a Python 3 virtual environment. Followed the same steps as @goodhamgupta. Everything worked correctly.  I believe that the key step to do is to run the` setup.py` installation script. In earlier attempts I had forgotten to do this and ended up with similar errors (missing modules).

**Comment by eriklindernoren** [comment]
I'll close this because of inactivity.
