### ISSUE TITLE
Demo.py AttributeError: no attribute 'solvers'

### ISSUE THREAD

**Issue by indrajithi** [eriklindernoren/ML-From-Scratch#8]
```
`Traceback (most recent call last):
  File "demo.py", line 23, in <module>
    from support_vector_machine import SupportVectorMachine
  File "/media/test/V2/lab/hack/ML-From-Scratch/supervised_learning/support_vector_machine.py", line 20, in <module>
    cvxopt.solvers.options['show_progress'] = False
AttributeError: 'module' object has no attribute 'solvers'`
```

**Comment by eriklindernoren** [comment]
Hmm, that's strange. Maybe if you tried 'pip install cvxopt --upgrade' and then run it? It works perfectly fine for me with the latest version.

**Comment by eriklindernoren** [comment]
Weird. You could of course always comment out that line. The only purpose of it is to hide
the output of cvxopt.
